homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages

  # Loads default set of integrations. Do not remove.
default_config:
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url: /www/community/lovelace-card-mod/card-mod.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
influxdb: !include influxdb.yaml
telegram_bot: !include includes/telegram.yaml
notify: !include includes/notify.yaml
recorder:
  purge_interval: 14
  purge_keep_days: 90
  exclude:
    entities:
      - sensor.time
media_player:
  - platform: aquostv
    host: 192.168.2.21
    name: media_player.android_tv_192_168_2_21
climate:
  - platform: smart_thermostat
    name: Smart Thermostat
    unique_id: smart_thermostat
    heater: switch.termostat_rele_kotla
    invert_heater: true
    target_sensor: sensor.temp2_temperature
    min_temp: 16
    max_temp: 26
    ac_mode: False
    target_temp: 22
    keep_alive:
      seconds: 60
    away_temp: 16
    sleep_temp: 20
    boost_temp: 23
    boost_pid_off: true
    kp: 25
    ki: 0.01
    kd: 200
    pwm: 00:20:00
    outdoor_sensor: sensor.temp1_temperature
    ke: 0.5