esphome:
  name: 111
  friendly_name: 111

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "7w0OSh2mzzjh7mttWNw/L9yyb2rhPhC2zwU+uK5AF2w="

ota:
  - platform: esphome
    password: "f95c349cad630d6cb4d815c5ad68501f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "111 Fallback Hotspot"
    password: "XqYAPKURyCUY"

captive_portal:
    