wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${node_name} Fallback"
    password: !secret ap_password

# captive_portal:

ota:
- platform: esphome
  password: !secret ota_password
  id: "${node_id}_ota"

api:
  reboot_timeout: 10min
  encryption:
    key: !secret api_encryption_key
