# Your Wi-Fi SSID and password
wifi_ssid: "VD83"
wifi_password: "1234q1234"
ap_password: "12345678"
ota_password: "36884af04ea2beafb42590be96a7284e"
api_encryption_key: "pH8xgBINjkJ/qEXtt60FvcZm+abJm3U/FvmLN4DuQ3U="
ota_password2: "f2f7caa2fa4d535036ffc1dbd7539402"
api_encryption_key2: "2jcv1ohrPzGrik2CnWYFAYeOKwc90Qc/Z4ATtE0xt3A="