esphome:
  name: testswitch
  friendly_name: TestSwitch

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "+kpW/8XZc8atYGG9m3lLsdG88eSMLkZVp0IsCpYHr38="

ota:
  - platform: esphome
    password: "54bf91a970d60661e685445975cd7623"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Testswitch Fallback Hotspot"
    password: "6ZW4Bk6H9NC4"

captive_portal:

web_server:
  port: 80

# Реле + виртуальные переключатели
switch:
  # Физическое реле
  - platform: gpio
    id: relay
    pin: 
      number: GPIO17
      inverted: true
    name: "Реле"

  # Виртуальный переключатель (Momentary)
  - platform: template
    id: momentary_switch
    name: "Реле (Momentary)"
    optimistic: true
    turn_on_action:
      - switch.turn_on: relay
    turn_off_action:
      - switch.turn_off: relay

# Виртуальная кнопка для переключения реле
button:
  - platform: template
    name: "Реле (Toggle)"
    on_press:
      - switch.toggle: relay
