esphome:
  name: "${device_name}"
  friendly_name: "${node_name}"
  comment: "Monitor and control a PowMr inverter and JK-BMS"
  includes:
    - "powmr-bms/helpers"
  project:
    name: "odya.esphome-powmr-hybrid-inverter"
    version: 1.3.3

packages:
  inverter: !include {
    file: modules/inverter.yaml
  }
  jkbms: !include {
    file: modules/jkbms.yaml
  }
#  debug: !include modules/debug.yaml

logger:
  baud_rate: 0


